### ISSUE TITLE
Show permissions for all modules and all roles by default

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/filter_perms#10]
With this module, the page `admin/config/people/permissions` doesn't show much information out of the box. I see the filters and I'm asked to »select at least one value from both the Roles and Modules select boxes above and then click the "Filter Permissions" button«. That's a lot! In my opinion it would be better to select 'All Roles' and 'All Modules' by default. What do others think about it?

**Comment by yorkshire-pudding** [comment]
@olafgrabienski - this could be an improvement, though if you have more checkboxes than can be saved maybe not.  I think for the majority of users, what you suggest would be an improvement.

I was wondering also whether it should be auto-submit so you don't need to press 'filter permissions' button but it just updates as selections are changed.

**Comment by olafgrabienski** [comment]
Thanks for your feedback! I guess I didn't understand what you mean by "if you have more checkboxes than can be saved maybe not".

Btw, I tested the module coming from https://github.com/backdrop/backdrop-issues/issues/5796, which asks to integrate *Filter Permissions* into Backdrop core. And I thought, if that happens, the default behavior should be more consistent with other filterable Backdrop pages.

**Comment by yorkshire-pudding** [comment]
> I guess I didn't understand what you mean by "if you have more checkboxes than can be saved maybe not".

While one purpose of the module is pure usability, another is the ability to save permission forms if they have more checkboxes than can be saved.  See the README:

> Sites that have one or more of the following factors may struggle to save the permissions form:
> 
> -  a large number of modules that have permissions attached
> - a large number of content types
> - a large number of roles
>
> While there are some functions within Backdrop that try to mitigate this, on some hosting it may not be possible to adjust (see the [documentation page](https://docs.backdropcms.org/max-input-vars)) and this module can enable saving of permissions, where it would not otherwise be possible to save.
> 
> Filter Permissions does this by only saving the visible permissions.

I have an idea how to mitigate this (PR on the way)

After further investigation, auto-submit won't work if the use case above is in play as the checkboxes would still be on screen.

**Comment by yorkshire-pudding** [comment]
@olafgrabienski @bugfolder @stpaultim 

I've added a PR to change the default filters to be "All roles" and "All modules".  I've also added a test to see if the form has too many checkboxes to save; if it does, a warning is displayed and the save button is hidden.

This can be tested by reducing `max_input_vars` in the Backdrops .htaccess file

![image](https://user-images.githubusercontent.com/20357797/198123339-2d081c58-d1f8-489d-a89c-76e3fbdc670d.png)


What do you think?

**Comment by olafgrabienski** [comment]
@yorkshire-pudding Thanks for the helpful clarification, and for the PR! I like the approach shown in the screenshot (no time for testing at the moment), and I'm also curious what Robert and Tim think about it.

**Comment by yorkshire-pudding** [comment]
I discussed with @stpaultim during office hours 19 today and he supports the change. Let's see what @bugfolder thinks

**Comment by bugfolder** [comment]
![permissions](https://user-images.githubusercontent.com/29214084/198142844-bfbd919b-ea4b-4aa6-b76e-8e9d5785301d.jpg)

This warning alone is worth the price of admission. 👍🙏😄 And this module should be in core!

**Comment by bugfolder** [comment]
Oh, for the record: WFM and LGTM.

**Comment by stpaultim** [comment]
> I discussed with @stpaultim during office hours 19 today and he supports the change.

Confirmed. I think is a great improvement.
