### ISSUE TITLE
Alphabetize module list in filter

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/filter_perms#4]
https://github.com/backdrop-contrib/filter_perms/issues/3 changed the module listing to list modules by their human-readable name (which matches the grouping titles on the permissions page). Yay! But the filter listing is still alphabetized by machine name, which is why, for example, with an Ubercart installation, the "Cart Links" module appears far down in the list (because its machine name is `uc_cart`). So it would be nice to sort the module list alphabetically by human name, so its order more closely matches the order of the grouped permissions.

**Comment by yorkshire-pudding** [comment]
I'm enjoying these little challenges @bugfolder
