### ISSUE TITLE
Add mention in README about the use case of too many checkboxes to save permissions

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/filter_perms#5]
Following a brief exchange on Zulip, decided it would be a good idea to mention this use case:
https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Contrib/near/301286067

**Comment by yorkshire-pudding** [comment]
@bugfolder - please can you have a look at the wording and check if (a) it makes sense and (b) covers everything and (c) whether there is room for improvement?  Thanks

**Comment by bugfolder** [comment]
Looks good.

**Comment by yorkshire-pudding** [comment]
Thanks @bugfolder
